### ISSUE TITLE
com.redhat.rhsa-RHEL7/8.xml.bz2 not found

### ISSUE THREAD

**Issue by jseiser** [OpenSCAP/openscap#2002]
#### Description of Problem:

Openscap now fails when running against RHEL 7 and 8 boxes because it cant not find `[com.redhat.rhsa-RHEL7.xml.bz2](https://access.redhat.com/security/data/oval/com.redhat.rhsa-RHEL7.xml.bz2)` or `https://access.redhat.com/security/data/oval/com.redhat.rhsa-RHEL8.xml.bz2`
 
#### OpenSCAP Version:
Installing: openscap;1.3.7-1.el8;x86_64;ubi-8-appstream-rpms
Installing: openscap-scanner;1.3.7-1.el8;x86_64;ubi-8-appstream-rpms

#### Operating System & Version:
RHEL 7 and RHEL 8

#### Steps to Reproduce:
Ansible

```
    - name: Install openscap scanner
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      become: true
      with_items:
        - openscap-scanner
        - scap-security-guide

    - name: Run Openscap Block
      block:
        - name: Run openscap # noqa ignore-errors
          ansible.builtin.command: oscap xccdf eval \
            --profile xccdf_org.ssgproject.content_profile_stig \
            --results-arf /tmp/oscap-arf.xml \
            --report /tmp/oscap-report.html \
            --fetch-remote-resources \
            /usr/share/xml/scap/ssg/content/ssg-{{ OS }}-ds.xml
          changed_when: false
          ignore_errors: true
          become: true
```

#### Actual Results:
```
 Downloading: https://access.redhat.com/security/data/oval/com.redhat.rhsa-RHEL7.xml.bz2 ... ok\nOpenSCAP Error: Premature end of data in tag html line 5
```

#### Expected Results:
To be able to reach this file

#### Additional Information / Debugging Steps:

The two files in question, appear to no longer exist on RHEL's site.  I assume this issue really goes back to them, but i cant figure out how how openscap decides where to get these files from.
