### ISSUE TITLE
Ansible playbooks generated by "oscap xccdf generate fix" fail to run in ansible Check mode

### ISSUE THREAD

**Issue by phess** [OpenSCAP/openscap#2205]
# Steps to reproduce

On a RHEL 9 system, run the command below to generate an ansible playbook to implement PCI-DSS compliance:
```
$ oscap xccdf generate fix \
    --profile pci-dss \
    --fix-type ansible \
    /usr/share/xml/scap/ssg/content/ssg-rhel9-ds.xml > \
      implement-pci-dss-on-rhel9.yml
``` 

Run the generated "implement-pci-dss-on-rhel9.yml" playbook in Check mode:
```
$ ansible-playbook -C -i my-inventory.ini implement-pci-dss-on-rhel9.yml
```

Outcome: it fails with this message (reformatted for clarity, although the fix suggestion given by ansible does not apply to the issue at hand):
```
TASK [Limit Password Reuse: password-auth - Check if any custom profile with the same name was already created] ****************************
fatal: [localhost]: FAILED! => {"msg":

The conditional check 'authselect_current_profile is not match("custom/")' failed. The error was: error while evaluating conditional (authselect_current_profile is not match("custom/")): 'authselect_current_profile' is undefined. 'authselect_current_profile' is undefined

The error appears to be in '/home/cloud-user/implement-pci-dss-on-rhel9.yml': line 643, column 11, but may be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

        - name: 'Limit Password Reuse: password-auth - Check if any custom profile with
          ^ here

This one looks easy to fix. It seems that there is a value started
with a quote, and the YAML parser is expecting to see the line ended
with the same kind of quote. For instance:

    when: "ok" in result.stdout

Could be written as:

   when: '"ok" in result.stdout'

Or equivalently:

   when: "'ok' in result.stdout"
}
```

Run the same playbook not in Check mode but in the default Run mode:
```
$ ansible-playbook -i my-inventory.ini implement-pci-dss-on-rhel9.yml
```

Outcome: it runs successfully.

# Description

On a RHEL9 system, the "oscap" tool can generate e.g. a pci-dss "fix" in ansible playbook format with the command below:
```
$ oscap xccdf generate fix \
    --profile pci-dss \
    --fix-type ansible \
    /usr/share/xml/scap/ssg/content/ssg-rhel9-ds.xml
```

The generated playbook runs fine if called like this and implements PCI-DSS compliance on the target host(s) from the inventory:
```
$ ansible-playbook -i $INVENTORY $GENERATED_PLAYBOOK
```

However, if one wishes to just check what _would_ be done on target hosts then ansible's Check mode can be leveraged:
```
$ ansible-playbook -C -i $INVENTORY $GENERATED_PLAYBOOK
```

This bug is about Check mode failing to run.

In this particular case I investigated, Check mode fails to run because some ansible tasks are skipped in Check mode but some later tasks require variables that would have been set by said skipped tasks. 

Ansible's Check mode skips all tasks that run commands. The generated playbook mentioned above contains tasks like this one below, which is skipped in Check mode because it runs a command on the target host:
```
- name: 'Limit Password Reuse: password-auth - Get authselect current profile'
  ansible.builtin.shell:
    cmd: authselect current -r | awk '{ print $1 }'
  register: result_authselect_profile
  changed_when: false
  when:
  - result_authselect_check_cmd is success
```

As a result, the `result_authselect_profile` variable (containing the outcome) is registered as skipped.

A few tasks further down the playbook, an ansible.builtin.set_fact task would run in Check mode, but it is skipped because of its `when` condition: it only runs when `result_authselect_profile` is not skipped. So this task is skipped in Check mode because of the previous one shown above.
```
- name: 'Limit Password Reuse: password-auth - Define the new authselect custom
profile as a local fact'
ansible.builtin.set_fact:
  authselect_current_profile: '{{ result_authselect_profile.stdout }}'
  authselect_custom_profile: custom/hardening
when:
- result_authselect_profile is not skipped
- result_authselect_profile.stdout is not match("custom/")
```

As a result of this task above being skipped, the "authselect_current_profile" and "authselect_custom_profile" variables are not set.

Finally, a few tasks further down the playbook, another task that is fine to run in Check mode is not skipped. Its "when" condition tries to read the "authselect_current_profile" variable. But this variable is not defined as the previous task displayed above was skipped.
```
- name: 'Limit Password Reuse: password-auth - Check if any custom profile with
    the same name was already created'
ansible.builtin.stat:
  path: /etc/authselect/{{ authselect_custom_profile }}
register: result_authselect_custom_profile_present
changed_when: false
when:
- authselect_current_profile is not match("custom/")
```

As a result, this last task above fails and the playbook halts with a failure.

Note that in ansible's (default) Run mode where actions are really executed, the playbook runs to completion and applies all the changes required to implement PCI-DSS compliance as originally requested by the user.

# Suggested fix

Ansible's Check mode will by default skip tasks that run commands. The playbook generated by "oscap" could have those particular tasks that run harmless commands – e.g. the `authselect current -r | awk '{ print $1 }'` task pasted at the top of this bug report – also run in Check mode by [adding an attribute](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_checkmode.html#enforcing-or-preventing-check-mode-on-tasks) to them:
```
- name: 'Limit Password Reuse: password-auth - Get authselect current profile'
ansible.builtin.shell:
  cmd: authselect current -r | awk '{ print $1 }'
register: result_authselect_profile
changed_when: false
check_mode: false     # <===== new attribute to run also in Check mode
when:
- result_authselect_check_cmd is success
```

By signalling harmless commands (i.e. commands that only read information but don't modify the system) the playbook generated by the `oscap` tool would successfully run in Check mode without compromising its effectiveness in any way when running in the default Run mode.
